-- MySQL Script generated by MySQL Workbench
-- Tue May 19 12:15:18 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
    `id_roles` INT NOT NULL AUTO_INCREMENT,
    `nombre_rol` VARCHAR(50) NOT NULL,
    `descripcion_rol` VARCHAR(300) NOT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP, -- CURRENT_TIMESTAMP: Valor fecha y hora
    `update_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, -- ACTUALIZA LA FECHA Y HORA
    `created_by` INT NULL,
    `deleted` TINYINT(1) DEFAULT 0, -- Bórrado lógico -- No se borra el registro fisicamente
    -- Borrado lógico - No se borra el registro fisicamente
    PRIMARY KEY (`id_roles`))
ENGINE = InnoDB;

-- DIEGO MUERE - DEBEMOS SACARLO DEL SISTEMA. BORRADO FISICO DELETE FROM USUARIO
-- CON DELETE EL DATO DEJA DE EXISTIR - NO SE PUEDE RECUPERAR
-- EN CAMBIO BORRADO LÓGICO (campo deleted activo - deleted 1))
-- PODEMOS OCULTAR EL USUARIO PARA QUE EL CLIENTE NO LO VEA
-- PERO NO SALE DEL SISTEMA.


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
    `id_usuario` INT NOT NULL AUTO_INCREMENT,
    `nombre_user` VARCHAR(100) NOT NULL,
    `email` VARCHAR(200) NOT NULL,
    `password_hash` VARCHAR(250) NOT NULL,
    `created_at` DATETIME NULL,
    `updated_at` DATETIME NULL,
    `created_by` INT NULL,
    `deleted` TINYINT(1) NULL,
    `id_roles` INT NOT NULL,
    PRIMARY KEY (`id_usuario`),
    UNIQUE INDEX `id_tipo_usuario_UNIQUE` (`id_usuario` ASC) VISIBLE,
    UNIQUE INDEX `nombre_user_UNIQUE` (`nombre_user` ASC) VISIBLE,
    UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
    INDEX `fk_usuario_roles_idx` (`id_roles` ASC) VISIBLE,
    CONSTRAINT `fk_usuario_roles`
    FOREIGN KEY (`id_roles`)
    REFERENCES `mydb`.`roles` (`id_roles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mensajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mensajes` (
    `id_mensajes` INT NOT NULL AUTO_INCREMENT,
    `contenido` TEXT NOT NULL,
    `created_at` DATETIME NULL,
    `update_at` DATETIME NULL,
    `created_by` INT NULL,
    `deleted` TINYINT(1) NULL,
    `id_usuario` INT NOT NULL,
    `id_usuario` INT NOT NULL,
    PRIMARY KEY (`id_mensajes`),
    INDEX `fk_mensajes_usuario1_idx` (`id_usuario` ASC) VISIBLE,
    INDEX `fk_mensajes_usuario2_idx` (`id_usuario` ASC) VISIBLE,
    CONSTRAINT `fk_mensajes_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_mensajes_usuario2`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comentarios` (
    `id_comentarios` INT NOT NULL AUTO_INCREMENT,
    `contenido` TEXT NOT NULL,
    `created_at` DATETIME NULL,
    `update_at` DATETIME NULL,
    `created_by` INT NULL,
    `deleted` TINYINT(1) NULL,
    `id_usuario` INT NOT NULL,
    PRIMARY KEY (`id_comentarios`),
    INDEX `fk_comentarios_usuario1_idx` (`id_usuario` ASC) VISIBLE,
    CONSTRAINT `fk_comentarios_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;